language: node_js
node_js:
  - node # uses most recent stable node version
services:
  - postgresql # starts up postgres
addons:
  postgresql: '9.6' # highest available postgres version on Travis
dist: trusty # uses trusty environment
sudo: false # when on trusty, uses Docker containers for speed
notifications:
  email:
    on_success: change # default: change (only when going from broken to fixed)
    on_failure: always # default: always (which is annoying, as it should be)
install:
  - npm ci # faster, goes only from package-lock
before_script:
  - psql -c 'create database "deployment-exercise-test";' -U postgres # remember to change this name if you change it elsewhere (e.g. package.json)

#  before_deploy:
#  - npm run build-client # make the bundle
#  - rm -rf node_modules # omit from the tarball, since we skip cleanup
# deploy:
#  skip_cleanup: true # prevents travis from deleting the build
# provider: heroku
# app: protected-castle-61698 # see README
# api_key: 62e5afc3-65a0-4310-969f-d8a4219e29c9
# secure: FIG6JG52OxmdwsckFB5bAo6ZqRBDwI2VR5SvcpXEiUSG+pIlmNcNHRPmHQ0ke8g/6lPQengOHw3fmSGqvHXYLIJPvNMb2cVxl1bb36/FRyFV7j6sXsO77iMbMgEGksW58+QqgAVMtOkcvxihlro2qV0Zi7/LbgcO2k9B6cjuQXk33SZz8oceQn6Am0NRS4R7j8/rvKFLvPi9It2DOLLsYY1Q83Y4FTXV03ss1oHjLYA8bOobvXtAnqPYKd5miGfYexLboxwSi2qez+iawsR6hlRWz5pRAq4hQU/DWjE0CdAqQJuzK+x25C04W9oKle8Tlp2T+fqKxQdEDFJ1JhsTQGfWt80BrcgM3zOqyQZeQgBKNXQKuztiMLHley0hflz5zrpXKZGwPCpT9EkgpuynBsO8LG8kjgFqWZn1+KbGmor+FwbhDOkNTMDaGV72gMw1N3NFOo5pMQ85y1Nav015iO5kxgNcbWeloidQv4g/tNLjrdTrbQ+T20nu5KlcSqukwAmHCJ9mFZPVpHpy42Yik+NAw4srzzzESUw7jrHdlNhkf9K2GVbfS4b/dCPPcNHef3NnY3zOxVfelP1MZ5vhL6OyNhZDzzFHTHA2x1tkx45SQgOuKKszteuKxG6WsE4ekOHRZEKDs6kQZ6r1XcZxbt9YrGjxv27SCc3XBH23M80=
